import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppSidebar } from "@/components/AppSidebar";
import "./globals.css";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/sonner"
import { ReactNode } from "react"
import { EditorContextProvider } from "@/components/EditorContext";

interface RootLayoutProps {
  children: ReactNode
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EditorContextProvider>
          <SidebarProvider defaultOpen={true}>
            <AppSidebar/>
            <SidebarInset>
              <SidebarTrigger />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </EditorContextProvider>
        <Toaster />
      </body>
    </html>
  )
}
